name: Selenium test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Selenium:
    runs-on: ubuntu 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
      
    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@master
      with:
        chromedriver-version: 'latest'
      env:
        CHROMEWEBDRIVER: '/usr/local/bin/chromedriver'
      
    - name: Run Tests
      run: |
        python tests/selenium_test.py  
      
    - name: Publish Test Artifacts (Optional)
      if: failure() 
      uses: actions/upload-artifact@v2
      with:
        name: failed-screenshots
        path: ./screenshots/ 
